export const CLEAR_CREDENTIALS = 'CLEAR_CREDENTIALS';
export const CLEAR_TRADE_HISTORY = 'CLEAR_TRADE_HISTORY';
export const FORGET_SYMBOL = 'FORGET_SYMBOL';
export const SET_CREDENTIALS = 'SET_CREDENTIALS';
export const SET_REMEMBER_CREDENTIALS = 'SET_REMEMBER_CREDENTIALS';
export const SET_TRADE_HISTORY_LOADING = 'SET_TRADE_HISTORY_LOADING';
export const UPDATE_TRADE_HISTORY = 'UPDATE_TRADE_HISTORY';
